export enum Role {
  ROLE_ADMIN = 'ROLE_ADMIN',
  ROLE_DEANERY = 'ROLE_DEANERY',


  ROLE_LECTERN = 'ROLE_LECTERN',
  ROLE_LECTERN_HEAD = 'ROLE_LECTERN_HEAD',
  ROLE_LECTERN_DEPUTY_HEAD = 'ROLE_LECTERN_DEPUTY_HEAD',
  ROLE_LECTERN_LABORATORY_HEAD = 'ROLE_LECTERN_LABORATORY_HEAD',
  ROLE_LECTERN_TEACHER = 'ROLE_LECTERN_TEACHER',
  ROLE_LECTERN_ENGINEER = 'ROLE_LECTERN_ENGINEER',
  ROLE_LECTERN_METHODIST = 'ROLE_LECTERN_METHODIST',

}
